const express=require('express'),router=express.Router(),db=require('../db/database')
const getDetails=id=>db.prepare('SELECT value FROM class_details WHERE class_id=? ORDER BY id').all(id).map(d=>d.value)
router.get('/',(req,res)=>{const cls=db.prepare('SELECT * FROM classes WHERE user_id=? ORDER BY created_at DESC').all(req.query.user_id);res.json(cls.map(c=>({...c,details:getDetails(c.id)})))})
router.get('/:id',(req,res)=>{const c=db.prepare('SELECT * FROM classes WHERE id=?').get(req.params.id);if(!c)return res.status(404).json({error:'Clase no encontrada'});res.json({...c,details:getDetails(c.id)})})
router.post('/',(req,res)=>{const{user_id,name,details}=req.body;if(!user_id||!name)return res.status(400).json({error:'user_id y name requeridos'});const r=db.prepare('INSERT INTO classes(user_id,name)VALUES(?,?)').run(user_id,name);const cid=r.lastInsertRowid;if(details&&Array.isArray(details)){const s=db.prepare('INSERT INTO class_details(class_id,label,value)VALUES(?,?,?)');details.forEach(d=>typeof d==='string'?s.run(cid,d,d):s.run(cid,d.label||d.value,d.value||d.label))}
const ps=db.prepare('INSERT INTO periods(class_id,name,weight,position)VALUES(?,?,?,?)');['Primer parcial','Segundo parcial','Tercer parcial'].forEach((p,i)=>ps.run(cid,p,33.33,i));const mr=db.prepare('INSERT INTO evaluation_models(class_id,name)VALUES(?,?)').run(cid,'Modelo predeterminado');const mid=mr.lastInsertRowid;const ts=db.prepare('INSERT INTO model_traits(model_id,trait_type,weight)VALUES(?,?,?)');[['actividades',15],['tareas',15],['proyecto',30],['examen',40],['practicas',0],['asistencia',0],['trabajos',0]].forEach(([t,w])=>ts.run(mid,t,w));res.json({id:cid,user_id,name,color:'#c0185a',details:getDetails(cid)})})
router.patch('/:id',(req,res)=>{const{color,name,highlight_field1,highlight_field2}=req.body;const f=[],v=[];if(color!==undefined){f.push('color=?');v.push(color)}if(name!==undefined){f.push('name=?');v.push(name)}if(highlight_field1!==undefined){f.push('highlight_field1=?');v.push(highlight_field1)}if(highlight_field2!==undefined){f.push('highlight_field2=?');v.push(highlight_field2)}if(f.length){v.push(req.params.id);db.prepare(`UPDATE classes SET ${f.join(',')} WHERE id=?`).run(...v)}const u=db.prepare('SELECT * FROM classes WHERE id=?').get(req.params.id);res.json({...u,details:getDetails(req.params.id)})})
router.delete('/:id',(req,res)=>{const{user_id,nip}=req.body;if(!db.prepare('SELECT id FROM users WHERE id=? AND nip=?').get(user_id,nip))return res.status(403).json({error:'NIP incorrecto'});db.prepare('DELETE FROM classes WHERE id=? AND user_id=?').run(req.params.id,user_id);res.json({success:true})})
module.exports=router
