require('dotenv').config()
const express=require('express'),cors=require('cors'),app=express(),PORT=process.env.PORT||3001
const db=require('./db/database')
app.use(cors())
app.use(express.json())
app.use('/api/auth',require('./routes/auth'))
app.use('/api/classes',require('./routes/classes'))
app.use('/api/students',require('./routes/students'))
app.use('/api/periods',require('./routes/periods'))
app.use('/api/attendance',require('./routes/attendance'))
app.use('/api/evidences',require('./routes/evidences'))
app.use('/api/calendar',require('./routes/calendar'))
app.get('/api/health',(req,res)=>res.json({status:'ok'}))
db.init().then(()=>{
  app.listen(PORT,()=>console.log(`✅ Servidor en http://localhost:${PORT}`))
}).catch(e=>{console.error('❌ No se pudo iniciar la base de datos:',e.message);process.exit(1)})
