const express=require('express'),cors=require('cors'),app=express(),PORT=process.env.PORT||3001
app.use(cors({origin:['http://localhost:5173','http://localhost:5174']}))
app.use(express.json())
app.use('/api/auth',require('./routes/auth'))
app.use('/api/classes',require('./routes/classes'))
app.use('/api/students',require('./routes/students'))
app.use('/api/periods',require('./routes/periods'))
app.use('/api/attendance',require('./routes/attendance'))
app.use('/api/evidences',require('./routes/evidences'))
app.use('/api/calendar',require('./routes/calendar'))
app.get('/api/health',(req,res)=>res.json({status:'ok'}))
app.listen(PORT,()=>console.log(`✅ Servidor en http://localhost:${PORT}`))
