const BASE='/api'
async function req(method,path,body){const opts={method,headers:{'Content-Type':'application/json'}};if(body)opts.body=JSON.stringify(body);const res=await fetch(BASE+path,opts);const data=await res.json();if(!res.ok)throw new Error(data.error||'Error en el servidor');return data}
export const api={
  login:(e,n)=>req('POST','/auth/login',{employee_number:e,nip:n}),
  register:(e,n,name)=>req('POST','/auth/register',{employee_number:e,nip:n,name}),
  recover:(e,code,newNip)=>req('POST','/auth/recover',{employee_number:e,recovery_code:code,new_nip:newNip}),
  updateAccount:(d)=>req('PATCH','/auth/update',d),
  getClasses:(uid)=>req('GET',`/classes?user_id=${uid}`),
  getClass:(id)=>req('GET',`/classes/${id}`),
  createClass:(d)=>req('POST','/classes',d),
  updateClass:(id,d)=>req('PATCH',`/classes/${id}`,d),
  deleteClass:(id,uid,nip)=>req('DELETE',`/classes/${id}`,{user_id:uid,nip}),
  getStudents:(cid)=>req('GET',`/students?class_id=${cid}`),
  addStudent:(cid,name)=>req('POST','/students',{class_id:cid,full_name:name}),
  updateStudent:(id,name)=>req('PATCH',`/students/${id}`,{full_name:name}),
  deleteStudent:(id,uid,nip)=>req('DELETE',`/students/${id}`,{user_id:uid,nip}),
  getPeriods:(cid)=>req('GET',`/periods?class_id=${cid}`),
  savePeriods:(cid,periods)=>req('POST','/periods/save',{class_id:cid,periods}),
  updatePeriod:(id,d)=>req('PATCH',`/periods/${id}`,d),
  getModels:(cid)=>req('GET',`/periods/models/list?class_id=${cid}`),
  addModel:(cid,name)=>req('POST','/periods/models',{class_id:cid,name}),
  updateModel:(id,d)=>req('PUT',`/periods/models/${id}`,d),
  deleteModel:(id)=>req('DELETE',`/periods/models/${id}`),
  getAttendance:(cid,pid)=>req('GET',`/attendance?class_id=${cid}&period_id=${pid}`),
  saveAttendance:(d)=>req('POST','/attendance/save',d),
  getEvidences:(cid,pid)=>req('GET',`/evidences?class_id=${cid}&period_id=${pid}`),
  addEvidence:(d)=>req('POST','/evidences',d),
  deleteEvidence:(id)=>req('DELETE',`/evidences/${id}`),
  saveGrades:(eid,grades)=>req('POST',`/evidences/${eid}/grades`,{grades}),
  getPending:(uid)=>req('GET',`/evidences/pending?user_id=${uid}`),
  getEvents:(uid)=>req('GET',`/calendar?user_id=${uid}`),
  addEvent:(d)=>req('POST','/calendar',d),
  deleteEvent:(id)=>req('DELETE',`/calendar/${id}`),
}
